version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
  mnist:
    container_name: mnist
    build: .
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AIXBLOCK_USE_REDIS=true
      - HOST_NAME=https://dev.aixblock.io
      - NCCL_SOCKET_IFNAME=eth0
      - NCCL_NET_PLUGIN=""
      - NCCL_IB_DISABLE=1
      - NCCL_P2P_DISABLE=1
      - NCCL_DEBUG=INFO
    ports:
      - 9090:9090
      - 6006:6006
      - 23456:23456
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./data/server:/data"
      - "./logs:/app/logs"
